--- # Deploiment de docker et build et run  d'applications nodejs
- hosts: aptserver:appserver
  user: test
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
      achref: /home/test/nodeapps/achref/e-commerce-challenge
      imageachref: achref/e-commerce-challenge
      ahmed: /home/test/nodeapps/ahmed/E-commerce_Movies  
      imageahmed: ahmed/e-commerc-movies
      amen:  /home/test/nodeapps/amen/Projet-16-04-16
      imageamen: amen/projet-16-04-16
      hamza: /home/test/nodeapps/hamza/CraftAcad-E-com
      imagehamza: hamza/e-com
      khalil: /home/test/nodeapps/khalil/test-craftacademy
      imagekhalil: khalil/test-craftacademy
      sadok:  /home/test/nodeapps/sadok/MEANBusiness
      imagesadok: sadok/meanbusiness

  tasks:
    - name: Installer curl pour centos
      yum: pkg=curl state=latest update_cache=yes
      when: "ansible_os_family == 'RedHat'"
    - name: installation docker sur un serveur centos
      shell: curl -fssl https://get.docker.com/ | sh > /home/test/logDocker.log
      when: "ansible_os_family == 'RedHat'"
  
    - name: mis à jour pour des serveurs ubuntu
      raw: apt-get update -y 
      when: "ansible_os_family == 'Debian'"
    - name:  installer docker sur serveur unbuntu
      apt: pkg=docker.io state=latest
      when: "ansible_os_family == 'Debian'"
    - name: lancement de  docker
      service: name=docker state=restarted

    - name: creer le  dossier de l'application chez le host
      file: name={{ item }} state=directory
      with_items:
        - "{{ achref }}"
        - "{{ ahmed }}"
        - "{{ amen }}"
        - "{{ hamza }}"
        - "{{ khalil }}"
        - "{{ sadok }}"


    - name: Copier contenu des applications chez le host
      action: copy src={{ item }}/ dest={{item }}/ 
      with_items:
        - "{{ achref }}"
        - "{{ ahmed }}"
        - "{{ amen }}"
        - "{{ hamza }}"
        - "{{ khalil }}"
        - "{{ sadok }}"
  
    - name: creation du script  demarrage mongodb et nodejs dans le contenair docker
      shell: echo "#!/bin/bash" > {{ item }}/myStartupScript.sh
      with_items:
        - "{{ achref }}"
        - "{{ ahmed }}"
        - "{{ amen }}"
        - "{{ hamza }}"
        - "{{ khalil }}"
        - "{{ sadok }}"

    - shell: echo "mongod & nodejs server.js" >> {{ item }}/myStartupScript.sh 
      with_items:
        - "{{ achref }}"
        - "{{ ahmed }}"
        - "{{ amen }}"
        - "{{ hamza }}"
        - "{{ khalil }}"
        - "{{ sadok }}"


    - name: build de l'application de achref  et creation de son  image docker
      shell:
       cmd: docker build -t  {{ imageachref }} . 
       chdir: "{{ achref }}/" 
        
    - name: run de l'image de achref dans un contenair docker
      shell:  
       cmd: docker run -p 49610:8000 -dti {{ imageachref }}


    - name: build de l'application de ahmed  et creation de son  image docker
      shell:
       cmd: docker build -t  {{ imageahmed }} .
       chdir: "{{ ahmed }}/"       
    - name: run de l'image de ahmed dans un contenair docker
      shell:  
       cmd: docker run -p 49620:3000 -dti  {{ imageahmed }}


    - name: build de l'application de amen  et creation de son  image docker
      shell:
       cmd: docker build -t  {{ imageamen }} .
       chdir: "{{ amen }}/"        
    - name: run de l'image de amen  dans un contenair docker
      shell:  
       cmd: docker run -p 49630:8000 -dti  {{ imageamen }}


    - name: build de l'application de hamza  et creation de son  image docker
      shell:
       cmd: docker build -t  {{ imagehamza }} .
       chdir: "{{ hamza }}/"       
    - name: run de l' application de hamza dans un contenair docker
      shell:  
       cmd: docker run -p 49640:3000 -dti  {{ imagehamza }}


    - name: build de l'application de khalil  et creation de son  image docker
      shell:
       cmd: docker build -t  {{ imagekhalil }} .
       chdir: "{{ khalil }}/"        
    - name: run de l' application de khalil dans un contenair docker
      shell:  
       cmd: docker run -p 49650:3000 -dti {{ imagekhalil }}



    - name: build de l'application de sadok  et creation de son  image docker
      shell:
       cmd: docker build -t  {{ imagesadok }} .
       chdir: "{{ sadok }}/"       
    - name: run de l' application de sadok dans un contenair docker
      shell:  
       cmd: docker run -p 49660:3000 -dti   {{ imagesadok }}
  

